config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homepage#index'

  resources :categories

  resources :posts

  get '/about', to: 'homepage#about'
  get '/cookies', to: 'homepage#cookies'
  get '/users/sign_in', to: 'devise/session#new'
  get '/users/sign_up', to: 'devise/registrations#new'

  get '/my_posts', to: 'posts#user_posts'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts, through: :post_categories
  
  validates :name, presence: true, uniqueness: true
end

app/models/null_objects/user.rb
module NullObjects
  class User
    def id
      nil
    end

    def posts
      nil
    end

    def is_admin?
      false
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  scope :featured_posts, lambda {
                                  includes(:categories)
                                    .order('created_at DESC')
                                    .limit(10)
                                }
  belongs_to :user
  has_many :post_categories
  has_many :categories, through: :post_categories
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  def current_user
    if session['warden.user.user.key']
      super
    else
      @current_user ||= NullObjects::User.new
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #TODO: authorization with pundit gem

  before_action :fetch_category, only: %i[show edit update destroy]
  before_action :authorize_category, only: %i[edit update destroy]


  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.valid? ? create_category : handle_category_validation_error
  end

  def show; end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = "Category #{@category.name} deleted"
    redirect_to categories_path
  end

  private

  def create_category
    @category.save
    flash[:notice] = 'Category created!'
    redirect_to category_path(@category)
  end

  def handle_category_validation_error
    flash[:errors] = @category.errors.full_messages
    redirect_back(fallback_location: root_path)
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def fetch_category
    @category = Category.find(params[:id])
  end

  def authorize_category
    authorize @category
  rescue Pundit::NotAuthorizedError
    authorization_failed
  end

  def authorization_failed
    flash[:notice] = 'You are not an admin!'
    redirect_to root_path
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index;
    @categories = Category.all
    # zmniejsza ilosc zapytan do bazy z n+1 do wymaganego minimum
    #n+1 to nadmiarowa ilosc zapytan do bazy; niezoptymalizowane zapytanie do bazy, ktore wykonuje sie niepotrzebnie wiele
    # przy wyswietlaniu posta idzie zapytanie do bazy o posty wraz z kategoriami
    @featured_posts = Post.featured_posts
  end

  def about; end

  def cookies; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :fetch_post, only: %i[show edit update destroy]
  before_action :authorize_post, only: %i[edit update destroy]

  def index
    @posts = Post.all.reverse
  end

  def user_posts
    @posts = current_user.posts
  end

  def new
    @post_form = PostForm.new
  end

  def create
    return unless params_have_valid_post_user_id
    @post_form = PostForm.new(post_form_params)
    @post_form.valid? ? create_post : handle_post_validation_failed
  end

  def show; end

  def edit
    @post_form = PostForm.new(@post)
  end

  def update
    @post_form = PostForm.new(post_form_params)
    UpdatePost.new(form_data: @post_form, post: @post).call
    redirect_to @post
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post #{@post.title} deleted"
    redirect_to posts_path
  end

  private

  def create_post
    post = Post.create(
      title: @post_form.title,
      description: @post_form.description,
      expiration_date: @post_form.expiration_date,
      user_id: @post_form.user_id
    )
    AssignCategoryToPost.new(category_id: @post_form.category_id, post: post).call
    flash[:notice] = 'Post created!'
    redirect_to post
  end

  def params_have_valid_post_user_id
    post_form_params[:user_id] == current_user.id.to_s
  end

  def handle_post_validation_failed
    flash[:errors] = @post_form.errors.full_messages
    redirect_back(fallback_location: root_path)
  end

  def post_form_params
    params.require(:post_form).permit(:title, :description, :expiration_date, :category_id, :user_id)
  end

  def fetch_post
    @post = Post.find(params[:id])
  end

  def authorize_post
    authorize @post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_signed_in?
    session['warden.user.user.key']
  end

  def sign_up_user_link
    link_to 'Sign up', new_user_registration_path
  end

  def login_or_logout_link
    user_signed_in? ? logout_user_link : login_user_link
  end

  def login_user_link
    login_tag = "<li>#{link_to 'Log in', new_user_session_path}</li>"
    login_tag.html_safe
  end

  def logout_user_link
    link_to 'Logout', destroy_user_session_path, method: :delete
  end

  def show_categories_for_admin
    categories_link_tag = "<li>#{link_to 'Categories', categories_path}</li>"
    categories_link_tag.html_safe if current_user.is_admin?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_owner_or_admin(post)
    (post.user_id == current_user.id) || current_user.is_admin?
  end
end

app/views/categories/_form.haml
= form_for @category do |f|
  = f.label :name
  = f.text_field :name
  = f.submit 'Submit'

app/views/categories/edit.haml
%h2 
	Edit category page
	= @category.name
	= link_to "Delete", @category, method: :delete, data: { confirm: "Are you sure?" }

= render 'form'

app/views/categories/index.haml
%p= button_to "Add category", new_category_path, method: :get, class: 'btn btn-lg btn-warning pull-right'
%p List of categories:
%ul
  - @categories.each do |category|
    %li= link_to category.name.capitalize, category

app/views/categories/new.haml
%h2 New Category
= render 'form'

app/views/categories/show.haml
%h2
  = @category.name.capitalize
  = link_to "Edit", edit_category_path(@category) if current_user.is_admin?

- @category.posts.each do |post|
  %p= link_to post.title, post

app/views/homepage/about.haml
.row
  .container
    %h2 About us!

app/views/homepage/cookies.haml
.row
  .container
    %h2 Welcome to the cookies clutch!

app/views/homepage/index.haml
.row.clearfix
  .container
    %h2.text-center What are you looking for today?
    .col-md-6.col-sm-offset-3
      %input.form-control{placeholder: 'I am searching for...', type: 'text'}
  .row.text-center
    - @categories.each do |category|
      = link_to category.name.capitalize, category
  .row.text-center
    - @featured_posts.each do |post|
      %p
        = link_to post.title, post
        Categories:
        - post.categories.each do |category|
          = category.name

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sellito</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/messages' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/_form.haml
= form_for @post do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :description
    = f.text_area :description
  %p
    = f.label :expiration_date
    = f.date_field :expiration_date
  = f.hidden_field :user_id, value: current_user.id
  %p= f.submit 'Submit'

app/views/posts/edit.haml
%h2
  Edit post:
  = @post.title
= form_for @post_form, url: post_path(@post), method: :patch do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :description
    = f.text_area :description
  %p
    = f.label :category
    = f.select :category_id, Category.all.collect { |c| [ c.name, c.id ] }, include_blank: true
  %p
    = f.label :expiration_date
    = f.date_field :expiration_date
  = f.hidden_field :user_id, value: current_user.id
  %p= f.submit 'Submit'

%p= button_to "Delete", @post, method: :delete, data: { confirm: "Ar ju śur?" }, class: 'btn btn-lg btn-warning'

app/views/posts/index.haml
%h1
  Posts
- if current_user
  %p= button_to "Add post", new_post_path, method: :get, class: 'btn btn-lg btn-warning'
%p List of posts:
%ul
  - @posts.each do |post|
    %li
      = link_to post.title, post
      = link_to "Edit", edit_post_path(post) if post_owner_or_admin(post)

app/views/posts/new.haml
%h2 New post
= form_for @post_form, url: posts_path, method: :post do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :description
    = f.text_area :description
  %p
    = f.label :category
    = f.select :category_id, Category.all.collect { |c| [ c.name, c.id ] }
  %p
    = f.label :expiration_date
    = f.date_field :expiration_date
  = f.hidden_field :user_id, value: current_user.id
  %p= f.submit 'Submit'

app/views/posts/show.haml
%h2
  = @post.title
  = link_to "Edit", edit_post_path(@post) if post_owner_or_admin(@post)
%p
  Expiration date:
  = @post.expiration_date.to_date

%p
  = @post.description

app/views/posts/user_posts.haml
%h1
  My posts
%p= button_to "Add post", new_post_path, method: :get, class: 'btn btn-lg btn-warning'
%p List of posts:
%ul
  - @posts.each do |post|
    %li
      = link_to post.title, post
      = link_to "Edit", edit_post_path(post)

app/views/shared/_footer.haml
%footer.footer
  .container.text-center
    %p.text-muted
      = link_to "Cookies", cookies_path

app/views/shared/_header.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      .navbar-brand
      = link_to image_tag("logo.png", size: "43x50"), root_path
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.pull-right
        %li
          = link_to 'Home', root_path
        %li
          = link_to 'About', about_path
        %li
          = link_to "Posts", posts_path
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle": "dropdown", type: "button"}
              Menu
              %span.caret
              %ul.dropdown-menu
                = show_categories_for_admin
                %li= link_to "My posts", my_posts_path
        %li
          %span.glyphicon.glyphicon-user
          = login_or_logout_link

app/views/shared/_messages.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-success"}
      %button.close{"aria-hidden": "true", "data-dismiss": "alert", type: "button"} &times;
      = content_tag :div, msg, id: "flash_success"
  - else
    %div{class: "alert alert-danger"}
      %button.close{"aria-hidden": "true", "data-dismiss": "alert", type: "button"} &times;
      - msg.each do |error|
        = content_tag :div, error, id: "flash_errors"